// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA84o-ga-TZgUshBvU5IJV82J09tMA_BQ',
    appId: '1:294430604784:web:0db41717e5f5c4a4b23135',
    messagingSenderId: '294430604784',
    projectId: 'bsapi-28f95',
    authDomain: 'bsapi-28f95.firebaseapp.com',
    databaseURL: 'https://bsapi-28f95-default-rtdb.firebaseio.com',
    storageBucket: 'bsapi-28f95.firebasestorage.app',
    measurementId: 'G-XFF5JSNMJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwicDo1DvY1rKotKBfTiKl2yQRIzlPe4A',
    appId: '1:294430604784:android:357a5204c8a590e9b23135',
    messagingSenderId: '294430604784',
    projectId: 'bsapi-28f95',
    databaseURL: 'https://bsapi-28f95-default-rtdb.firebaseio.com',
    storageBucket: 'bsapi-28f95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwPzwKXuDnNakOM6wxdYXvK9OBeqEHCM',
    appId: '1:294430604784:ios:961cb7e31f290f51b23135',
    messagingSenderId: '294430604784',
    projectId: 'bsapi-28f95',
    databaseURL: 'https://bsapi-28f95-default-rtdb.firebaseio.com',
    storageBucket: 'bsapi-28f95.firebasestorage.app',
    iosBundleId: 'com.tracker.trackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwPzwKXuDnNakOM6wxdYXvK9OBeqEHCM',
    appId: '1:294430604784:ios:961cb7e31f290f51b23135',
    messagingSenderId: '294430604784',
    projectId: 'bsapi-28f95',
    databaseURL: 'https://bsapi-28f95-default-rtdb.firebaseio.com',
    storageBucket: 'bsapi-28f95.firebasestorage.app',
    iosBundleId: 'com.tracker.trackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA84o-ga-TZgUshBvU5IJV82J09tMA_BQ',
    appId: '1:294430604784:web:92f5113aa1782e5ab23135',
    messagingSenderId: '294430604784',
    projectId: 'bsapi-28f95',
    authDomain: 'bsapi-28f95.firebaseapp.com',
    databaseURL: 'https://bsapi-28f95-default-rtdb.firebaseio.com',
    storageBucket: 'bsapi-28f95.firebasestorage.app',
    measurementId: 'G-8KFMPCK0ZW',
  );
}
